### ISSUE TITLE
Pet owner name is fetched on renderer thread, freezing the client when hovering a new pet

### ISSUE THREAD

**Issue by Scotsguy** [PotatoPresident/PetOwner#16]
https://github.com/PotatoPresident/PetOwner/blob/7df6d2e9cdf0abfbdd196fdeb688fe071df8fdb9/src/main/java/us/potatoboy/petowner/mixin/OwnerNameTagRendering.java#L50

Takes however long it takes to fetch a profile from Mojang, usually 0.5-1 seconds. That's an unacceptably long freeze.
Please offload fetching the profile to another thread and show a "please wait" message, or nothing at all, until that's done.

**Comment by PotatoPresident** [comment]
Yeah I know... Its just annoying using yggdrasil because there isn't a way that I've found to check if the name is in the cache. I suppose I'll have to cache the cache or something. I'll work on this.
