### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by Primka1** [PotatoPresident/PetOwner#8]
Does this mod need server support too? or is it just a bug, that when i try to use this, then it says "Something went wrong"
Version 1.16.1-1.3 and 1.16.1-1.1

**Comment by PotatoPresident** [comment]
The mod is entirely client side. Could you supply your latest.log from your clients logs folder? Usually that error means something is wrong with the uuid its getting from the pet. Are you on an offline server?

**Comment by Primka1** [comment]
-- latest log --

https://paste.gg/p/anonymous/49e127d819664b6ea1c1a55cfde00820

**Comment by PotatoPresident** [comment]
The dog owner uuid is not a valid minecraft account uuid. Nothing I can do about that. I'm guessing the server doesn't have bungeecord uuid forwarding setup correctly. Sorry!

**Comment by patrickpissurno** [comment]
Could you please add support for offline mode servers? I often host LAN parties with friends, and due to my poor mobile data carrier signal I can't use online mode. I guess it could be implemented by using the player name as a fallback, in case the uuid isn't available, but I'm not familiarized with the internals.

Would it be possible?

Thanks.

**Comment by yitzy299** [comment]
It’s not possible, and I’m not sure you excuse holds up - online mod isn’t intensive for data connection

**Comment by patrickpissurno** [comment]
I didn’t mean to give an excuse, at all. But just to make things clear, it’s not about bandwidth. It’s about signal intensity. It’s really unstable and most of the time I don’t have any signal. That’s what happens in underground rooms. Anyway, if it’s a limitation from a technical standpoint, or if the author simply doesn’t wanna implement it, that’s fine. No need to be rude.

**Comment by PotatoPresident** [comment]
The client only knows the UUID of the pet. To get the username it has to ask the Mojang API what it is. There is no way to get this information from somewhere else.
